"""
Comprehensive US-market vehicle make/model database.
Includes current and discontinued models so sellers can list any used vehicle.
"""

VEHICLE_MAKES_MODELS = {
    'Acura': [
        'CL', 'CSX', 'EL', 'ILX', 'Integra', 'Legend', 'MDX', 'NSX',
        'RDX', 'RL', 'RLX', 'RSX', 'SLX', 'TL', 'TLX', 'TSX', 'Vigor',
        'ZDX',
    ],
    'Alfa Romeo': [
        '147', '156', '159', '164', '4C', '4C Spider', 'Giulia',
        'Giulietta', 'GTV', 'Stelvio', 'Tonale',
    ],
    'AMC': [
        'AMX', 'Concord', 'Eagle', 'Gremlin', 'Hornet', 'Javelin',
        'Matador', 'Pacer', 'Rebel', 'Spirit',
    ],
    'Audi': [
        'A3', 'A4', 'A4 Allroad', 'A5', 'A6', 'A6 Allroad', 'A7', 'A8',
        'allroad', 'e-tron', 'e-tron GT', 'e-tron S', 'e-tron Sportback',
        'Q2', 'Q3', 'Q4 e-tron', 'Q5', 'Q7', 'Q8', 'Q8 e-tron',
        'R8', 'RS3', 'RS4', 'RS5', 'RS6', 'RS7', 'S3', 'S4', 'S5',
        'S6', 'S7', 'S8', 'SQ5', 'SQ7', 'SQ8', 'TT', 'TT RS', 'TTS',
    ],
    'BMW': [
        '1 Series', '2 Series', '2 Series Active Tourer', '3 Series',
        '3 Series Gran Turismo', '4 Series', '5 Series', '5 Series Gran Turismo',
        '6 Series', '6 Series Gran Coupe', '7 Series', '8 Series',
        'i3', 'i4', 'i5', 'i7', 'i8', 'iX', 'iX3',
        'M2', 'M3', 'M4', 'M5', 'M6', 'M8', 'M240i', 'M340i', 'M440i',
        'X1', 'X2', 'X3', 'X3 M', 'X4', 'X4 M', 'X5', 'X5 M',
        'X6', 'X6 M', 'X7', 'XM',
        'Z3', 'Z4',
    ],
    'Buick': [
        'Cascada', 'Century', 'Electra', 'Enclave', 'Encore',
        'Encore GX', 'Envision', 'Envista', 'LaCrosse', 'LeSabre',
        'Lucerne', 'Park Avenue', 'Rainier', 'Regal', 'Rendezvous',
        'Riviera', 'Skylark', 'Terraza', 'Verano',
    ],
    'Cadillac': [
        'ATS', 'ATS-V', 'CT4', 'CT4-V', 'CT5', 'CT5-V', 'CT6',
        'CTS', 'CTS-V', 'DeVille', 'DTS', 'Eldorado', 'Escalade',
        'Escalade ESV', 'Escalade EXT', 'LYRIQ', 'OPTIQ', 'Seville',
        'SRX', 'STS', 'XLR', 'XT4', 'XT5', 'XT6',
    ],
    'Chevrolet': [
        'Astro', 'Avalanche', 'Aveo', 'Blazer', 'Bolt EUV', 'Bolt EV',
        'Camaro', 'Captiva', 'Cavalier', 'City Express', 'Classic',
        'Cobalt', 'Colorado', 'Corvette', 'Cruze', 'Equinox', 'Equinox EV',
        'Express', 'Express Cargo', 'HHR', 'Impala', 'Lumina',
        'Malibu', 'Metro', 'Monte Carlo', 'Prizm', 'S10',
        'Silverado 1500', 'Silverado 2500HD', 'Silverado 3500HD',
        'Silverado EV', 'Sonic', 'Spark', 'SS', 'SSR',
        'Suburban', 'Tahoe', 'Tracker', 'Trailblazer', 'TrailBlazer EXT',
        'Traverse', 'Trax', 'Uplander', 'Venture', 'Volt',
    ],
    'Chrysler': [
        '200', '300', '300C', '300M', 'Aspen', 'Cirrus',
        'Concorde', 'Crossfire', 'LHS', 'New Yorker',
        'Pacifica', 'PT Cruiser', 'Sebring', 'Town & Country',
        'Voyager',
    ],
    'Dodge': [
        'Avenger', 'Caliber', 'Challenger', 'Charger', 'Dakota',
        'Dart', 'Durango', 'Grand Caravan', 'Hornet',
        'Intrepid', 'Journey', 'Magnum', 'Neon', 'Nitro',
        'Ram 1500', 'Ram 2500', 'Ram 3500', 'Sprinter', 'Stratus',
        'Viper',
    ],
    'Eagle': [
        'Summit', 'Talon', 'Vision',
    ],
    'Ferrari': [
        '296 GTB', '296 GTS', '458 Italia', '458 Spider', '488 GTB',
        '488 Pista', '488 Spider', '812 Competizione', '812 GTS',
        '812 Superfast', 'California', 'California T', 'F12berlinetta',
        'F40', 'F8 Spider', 'F8 Tributo', 'FF', 'GTC4Lusso',
        'Portofino', 'Portofino M', 'Purosangue', 'Roma', 'SF90 Spider',
        'SF90 Stradale',
    ],
    'Fiat': [
        '124 Spider', '500', '500 Abarth', '500c', '500e',
        '500L', '500X', 'Bravo', 'Punto',
    ],
    'Ford': [
        'Bronco', 'Bronco Sport', 'C-Max', 'C-Max Energi',
        'C-Max Hybrid', 'Contour', 'Crown Victoria', 'E-Series',
        'EcoSport', 'Edge', 'Escape', 'Escape Plug-in Hybrid',
        'Excursion', 'Expedition', 'Expedition EL', 'Expedition MAX',
        'Explorer', 'Explorer Sport Trac', 'F-150', 'F-150 Lightning',
        'F-250', 'F-350', 'F-450', 'Five Hundred', 'Flex',
        'Focus', 'Focus ST', 'Focus RS', 'Freestar', 'Freestyle',
        'Fusion', 'Fusion Energi', 'Fusion Hybrid', 'Galaxy',
        'Maverick', 'Mustang', 'Mustang Mach-E', 'Probe',
        'Ranger', 'Taurus', 'Taurus X', 'Thunderbird',
        'Transit', 'Transit Connect', 'Transit Cargo', 'Windstar',
    ],
    'Genesis': [
        'G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80',
    ],
    'GMC': [
        'Acadia', 'Canyon', 'Envoy', 'Envoy XL', 'Envoy XUV',
        'Jimmy', 'Safari', 'Sierra 1500', 'Sierra 2500HD', 'Sierra 3500HD',
        'Sierra EV', 'Sonoma', 'Terrain', 'Typhoon',
        'Yukon', 'Yukon XL',
    ],
    'Honda': [
        'Accord', 'Accord Crosstour', 'Accord Hybrid', 'Accord Plug-in Hybrid',
        'Civic', 'Civic Si', 'Civic Type R', 'Clarity',
        'CR-V', 'CR-V Hybrid', 'CR-Z', 'Crosstour', 'del Sol',
        'Element', 'Fit', 'HR-V', 'Insight', 'Odyssey',
        'Passport', 'Pilot', 'Prelude', 'Prologue',
        'Ridgeline', 'S2000',
    ],
    'Hummer': [
        'H1', 'H2', 'H3', 'H3T',
    ],
    'Hyundai': [
        'Accent', 'Azera', 'Elantra', 'Elantra GT', 'Elantra N',
        'Elantra Touring', 'Entourage', 'Equus', 'Genesis',
        'Genesis Coupe', 'IONIQ', 'IONIQ 5', 'IONIQ 5 N', 'IONIQ 6',
        'Kona', 'Kona Electric', 'Kona N', 'Nexo',
        'Palisade', 'Santa Cruz', 'Santa Fe', 'Santa Fe Hybrid',
        'Santa Fe Sport', 'Santa Fe XL', 'Sonata', 'Sonata Hybrid',
        'Sonata N Line', 'Tiburon', 'Tucson', 'Tucson Hybrid',
        'Tucson Plug-in Hybrid', 'Veloster', 'Veloster N',
        'Venue', 'Veracruz', 'XG350',
    ],
    'Infiniti': [
        'EX35', 'EX37', 'FX35', 'FX37', 'FX45', 'FX50',
        'G20', 'G25', 'G35', 'G37',
        'I30', 'I35',
        'J30', 'JX35', 'M30', 'M35', 'M37', 'M45', 'M56',
        'Q40', 'Q45', 'Q50', 'Q60', 'Q70',
        'QX30', 'QX4', 'QX50', 'QX55', 'QX56', 'QX60', 'QX70', 'QX80',
    ],
    'Isuzu': [
        'Amigo', 'Ascender', 'Axiom', 'i-280', 'i-290',
        'i-350', 'i-370', 'i-Series', 'Hombre',
        'Rodeo', 'Rodeo Sport', 'Trooper', 'VehiCROSS',
    ],
    'Jaguar': [
        'E-Pace', 'F-Pace', 'F-Type', 'I-Pace',
        'S-Type', 'X-Type', 'XE', 'XF', 'XJ', 'XJL', 'XK', 'XKR',
    ],
    'Jeep': [
        'Cherokee', 'Commander', 'Compass', 'Gladiator',
        'Grand Cherokee', 'Grand Cherokee 4xe', 'Grand Cherokee L',
        'Grand Wagoneer', 'Liberty', 'Patriot', 'Renegade',
        'Wagoneer', 'Wrangler', 'Wrangler 4xe', 'Wrangler Unlimited',
    ],
    'Kia': [
        'Amanti', 'Borrego', 'Cadenza', 'Carnival',
        'EV6', 'EV9', 'Forte', 'Forte Koup', 'K5', 'K900',
        'Magentis', 'Niro', 'Niro EV', 'Niro Plug-in Hybrid',
        'Optima', 'Optima Hybrid', 'Rio', 'Rondo',
        'Sedona', 'Seltos', 'Sephia', 'Sorento', 'Sorento Hybrid',
        'Soul', 'Soul EV', 'Spectra', 'Sportage',
        'Sportage Hybrid', 'Stinger', 'Telluride',
    ],
    'Lamborghini': [
        'Aventador', 'Aventador S', 'Aventador SVJ', 'Gallardo',
        'Huracán', 'Huracán EVO', 'Huracán STO', 'Murciélago',
        'Revuelto', 'Urus',
    ],
    'Land Rover': [
        'Defender', 'Discovery', 'Discovery 3', 'Discovery 4',
        'Discovery 5', 'Discovery Sport', 'Freelander',
        'LR2', 'LR3', 'LR4',
        'Range Rover', 'Range Rover Evoque', 'Range Rover Sport',
        'Range Rover Velar',
    ],
    'Lexus': [
        'CT 200h', 'ES 300', 'ES 300h', 'ES 330', 'ES 350',
        'GS 300', 'GS 350', 'GS 400', 'GS 430', 'GS 450h', 'GS 460', 'GS F',
        'GX 460', 'GX 470',
        'IS 200t', 'IS 250', 'IS 300', 'IS 350', 'IS 500', 'IS F',
        'LC 500', 'LC 500h', 'LFA',
        'LS 400', 'LS 430', 'LS 460', 'LS 500', 'LS 500h', 'LS 600h',
        'LX 450', 'LX 470', 'LX 570', 'LX 600',
        'NX 200t', 'NX 250', 'NX 300', 'NX 300h', 'NX 350', 'NX 350h', 'NX 450h+',
        'RC 200t', 'RC 300', 'RC 350', 'RC F',
        'RX 300', 'RX 330', 'RX 350', 'RX 350h', 'RX 350L', 'RX 400h', 'RX 450h',
        'RX 450h+', 'RX 500h',
        'SC 400', 'SC 430',
        'TX 350', 'TX 500h', 'TX 550h+',
        'UX 200', 'UX 250h',
    ],
    'Lincoln': [
        'Aviator', 'Blackwood', 'Continental', 'Corsair',
        'LS', 'Mark LT', 'Mark VIII', 'MKC', 'MKS',
        'MKT', 'MKX', 'MKZ', 'Navigator', 'Navigator L',
        'Town Car', 'Zephyr',
    ],
    'Maserati': [
        'Ghibli', 'GranCabrio', 'GranTurismo', 'Grecale',
        'Levante', 'MC20', 'Quattroporte',
    ],
    'Mazda': [
        'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-7', 'CX-9', 'CX-90',
        'Mazda2', 'Mazda3', 'Mazda5', 'Mazda6',
        'Millenia', 'MPV', 'MX-30', 'MX-5 Miata', 'MX-6',
        'Protege', 'Protege5', 'RX-7', 'RX-8',
        'Tribute',
    ],
    'McLaren': [
        '540C', '570GT', '570S', '600LT', '620R', '650S',
        '675LT', '720S', '750S', 'Artura', 'Elva', 'GT',
        'MP4-12C', 'Senna', 'Speedtail',
    ],
    'Mercedes-Benz': [
        'A-Class', 'AMG GT', 'AMG GT 4-Door',
        'B-Class', 'C-Class', 'C-Class Coupe', 'C-Class Estate',
        'CL-Class', 'CLA', 'CLA Shooting Brake', 'CLK-Class', 'CLS',
        'E-Class', 'E-Class Cabriolet', 'E-Class Coupe', 'E-Class Estate',
        'EQA', 'EQB', 'EQC', 'EQE', 'EQE SUV', 'EQS', 'EQS SUV',
        'G-Class', 'GLA', 'GLB', 'GLC', 'GLC Coupe', 'GLE', 'GLE Coupe',
        'GL-Class', 'GLS', 'GLK-Class',
        'M-Class', 'Metris',
        'R-Class', 'S-Class', 'S-Class Cabriolet', 'S-Class Coupe',
        'SL', 'SLC', 'SLK-Class', 'SLR McLaren', 'SLS AMG',
        'Sprinter',
    ],
    'Mercury': [
        'Cougar', 'Grand Marquis', 'Mariner', 'Milan',
        'Montego', 'Monterey', 'Mountaineer', 'Mystique',
        'Sable', 'Tracer', 'Villager',
    ],
    'Mini': [
        'Clubman', 'Convertible', 'Cooper', 'Cooper Clubman',
        'Cooper Convertible', 'Cooper Countryman', 'Cooper Coupe',
        'Cooper Paceman', 'Cooper Roadster', 'Cooper S',
        'Cooper SE', 'Countryman', 'Electric', 'Paceman',
    ],
    'Mitsubishi': [
        '3000GT', 'Diamante', 'Eclipse', 'Eclipse Cross',
        'Eclipse Cross PHEV', 'Endeavor', 'Expo',
        'Galant', 'Lancer', 'Lancer Evolution', 'Lancer Sportback',
        'Mirage', 'Mirage G4', 'Montero', 'Montero Sport',
        'Outlander', 'Outlander PHEV', 'Outlander Sport',
        'Raider', 'Sigma',
    ],
    'Nissan': [
        '200SX', '240SX', '300ZX', '350Z', '370Z',
        'Altima', 'Altima Hybrid', 'Ariya',
        'Armada', 'Cube', 'Frontier',
        'GT-R', 'Juke', 'Kicks', 'LEAF',
        'Maxima', 'Murano', 'Murano CrossCabriolet',
        'NV1500', 'NV2500', 'NV3500', 'NV200',
        'Pathfinder', 'Quest', 'Rogue',
        'Rogue Select', 'Rogue Sport', 'Sentra',
        'Stanza', 'Titan', 'Titan XD',
        'Versa', 'Versa Note', 'Xterra', 'Z',
    ],
    'Oldsmobile': [
        'Alero', 'Aurora', 'Bravada', 'Cutlass', 'Cutlass Supreme',
        'Intrigue', 'Silhouette', 'Toronado',
    ],
    'Plymouth': [
        'Breeze', 'Grand Voyager', 'Neon', 'Prowler', 'Voyager',
    ],
    'Pontiac': [
        'Aztek', 'Bonneville', 'Firebird', 'G5', 'G6', 'G8',
        'Grand Am', 'Grand Prix', 'GTO', 'Montana',
        'Solstice', 'Torrent', 'Trans Am', 'Vibe',
    ],
    'Porsche': [
        '718 Boxster', '718 Cayman', '718 Cayman GT4',
        '911', '911 Carrera', '911 Carrera 4', '911 GT3', '911 Targa', '911 Turbo',
        'Boxster', 'Cayenne', 'Cayenne Coupe', 'Cayenne E-Hybrid',
        'Cayman', 'Macan', 'Macan EV', 'Panamera', 'Panamera Sport Turismo',
        'Taycan', 'Taycan Cross Turismo', 'Taycan Sport Turismo',
    ],
    'Ram': [
        '1500', '1500 Classic', '2500', '3500',
        'C/V', 'ProMaster', 'ProMaster City',
    ],
    'Rivian': [
        'R1S', 'R1T', 'R2',
    ],
    'Rolls-Royce': [
        'Cullinan', 'Dawn', 'Ghost', 'Phantom', 'Silver Seraph',
        'Spectre', 'Wraith',
    ],
    'Saab': [
        '9-2X', '9-3', '9-5', '9-7X',
    ],
    'Saturn': [
        'Aura', 'Ion', 'L-Series', 'Outlook', 'Relay',
        'Sky', 'VUE',
    ],
    'Scion': [
        'FR-S', 'iA', 'iM', 'iQ', 'tC', 'xA', 'xB', 'xD',
    ],
    'Smart': [
        'Fortwo', 'Fortwo Cabriolet', 'Fortwo ED',
    ],
    'Subaru': [
        'Ascent', 'B9 Tribeca', 'BRZ', 'Crosstrek',
        'Crosstrek Hybrid', 'Forester', 'Impreza',
        'Legacy', 'Outback', 'Solterra',
        'SVX', 'Tribeca', 'WRX', 'WRX STI', 'XV Crosstrek',
    ],
    'Suzuki': [
        'Aerio', 'Equator', 'Forenza', 'Grand Vitara',
        'Kizashi', 'Reno', 'Swift', 'SX4', 'Verona', 'Vitara', 'XL-7',
    ],
    'Tesla': [
        'Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster',
    ],
    'Toyota': [
        '4Runner', 'Avalon', 'Avalon Hybrid', 'bZ4X',
        'C-HR', 'Camry', 'Camry Hybrid', 'Camry Solara',
        'Celica', 'Corolla', 'Corolla Cross', 'Corolla Cross Hybrid',
        'Corolla Hatchback', 'Corolla iM', 'Corolla Matrix',
        'Crown', 'Echo', 'FJ Cruiser', 'GR86', 'GR Corolla', 'GR Supra',
        'Highlander', 'Highlander Hybrid', 'Land Cruiser', 'Matrix',
        'MR2', 'MR2 Spyder', 'Mirai', 'Paseo',
        'Previa', 'Prius', 'Prius AWD-e', 'Prius c', 'Prius Prime',
        'Prius v', 'RAV4', 'RAV4 Hybrid', 'RAV4 Prime',
        'Sequoia', 'Sienna', 'Solara', 'Supra',
        'T100', 'Tacoma', 'Tercel',
        'Tundra', 'Tundra Hybrid',
        'Venza', 'Yaris', 'Yaris iA',
    ],
    'Volkswagen': [
        'Arteon', 'Atlas', 'Atlas Cross Sport', 'Beetle',
        'CC', 'Eos', 'Golf', 'Golf Alltrack', 'Golf GTI',
        'Golf R', 'Golf SportWagen',
        'ID.4', 'ID.Buzz',
        'Jetta', 'Jetta GLI', 'Jetta SportWagen',
        'New Beetle', 'Passat', 'Phaeton', 'Rabbit',
        'Routan', 'Taos', 'Tiguan', 'Tiguan Limited',
        'Touareg', 'Touareg 2',
    ],
    'Volvo': [
        'C30', 'C40 Recharge', 'C70',
        'EX30', 'EX90',
        'S40', 'S60', 'S60 Cross Country', 'S60 Recharge',
        'S70', 'S80', 'S90', 'S90 Recharge',
        'V40', 'V50', 'V60', 'V60 Cross Country', 'V60 Recharge',
        'V70', 'V90', 'V90 Cross Country', 'V90 Recharge',
        'XC40', 'XC40 Recharge', 'XC60', 'XC60 Recharge',
        'XC70', 'XC90', 'XC90 Recharge',
    ],
    'Wagoneer': [
        'Grand Wagoneer', 'Wagoneer',
    ],
}

# Sorted list of all makes for template iteration
VEHICLE_MAKES = sorted(VEHICLE_MAKES_MODELS.keys())
